# COMPARACION:OPERADOR DE IGUALDAD
print(2 == 2)
print(3 == 5)
print("si" == "si")
print(2 == 2.5)
print(2 == 2**2)

#IGUALDAD: EL OPERADOR IGUAL a (==)
a = input("ingrese su numero:")
b = input("escribe de nuevo tu contraseña:")
mensaje = a == b
if mensaje == True:
    print("contraseña correcta")
else: 
    print("contraseña incorecta")

var = 0  # Asignando 0 a var
print(var == 0)

var = 1  # Asignando 1 a var
print(var == 0)

#DESIGUALDAD: EL OPERADOR NO ES UGUAL a (!=)
var = 0  # Asignando 0 a var
print(var != 0)

var = 1  # Asignando 1 a var
print(var != 0)